version: '2.7'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  command: "php otel_worker.php"
  env:
    - OTEL_SERVICE_NAME: php
    - OTEL_TRACES_EXPORTER: otlp
    - OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    - OTEL_EXPORTER_OTLP_ENDPOINT: http://127.0.0.1:4318
    - OTEL_PHP_TRACES_PROCESSOR: simple
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers", "http_metrics" ]
  max_request_size: 20
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 100s
    destroy_timeout: 100s
    max_jobs: 10
    supervisor:
      max_worker_memory: 128
      exec_ttl: 100s
metrics:
  address: "127.0.0.1:2112"
logs:
  mode: production
  level: debug
  encoding: console
status:
    address: localhost:2114
