version: '2.7'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  relay: pipes
http:
  access_logs: true
  middleware: [ "static", "gzip", "headers", "http_metrics" ]
  max_request_size: 100
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 1h
    destroy_timeout: 1h
    max_jobs: 0
    supervisor:
      max_worker_memory: 128
      exec_ttl: 1h
metrics:
  address: "0.0.0.0:2112"
  collect:
    http:
      request_duration_seconds:
        buckets: [0.05, 0.1, 0.3, 1.2, 5.0]
    memory:
      enabled: true
    cpu:
      enabled: true
    gc:
      enabled: true
    go_routines:
      enabled: true
logs:
  mode: production
  level: debug
  encoding: console
status:
    address: localhost:2114
