version: '3'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers", "http_metrics" ]
  max_request_size: 256
  access_logs: true
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 1h
    destroy_timeout: 1h
    num_workers: 6
    max_queue_size: 0
    supervisor:
      max_worker_memory: 256
      exec_ttl: 1h
metrics:
  address: "0.0.0.0:2112"
logs:
  mode: production
  level: debug
  channels:
    http:
      file_logger_options:
        log_output: "/var/log/containers/http.log"
        max_age: 24
        compress: true
status:
    address: localhost:2114
