version: '2.7'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers", "http_metrics" ]
  max_request_size: 100
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 200s
    destroy_timeout: 200s
    max_jobs: 100
    supervisor:
      max_worker_memory: 128
      exec_ttl: 200s
metrics:
  address: "0.0.0.0:2112"
logs:
  mode: production
  level: debug
  encoding: console
status:
    address: localhost:2114
