version: '2.7'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers", "http_metrics" ]
  max_request_size: 20
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 100s
    destroy_timeout: 100s
    max_jobs: 10
    supervisor:
      max_worker_memory: 128
      exec_ttl: 100s
  kv:
  # User defined name of the storage.
  redis:
    # Required section.
    # Should be "redis" for the redis driver.
    driver: redis

    config:
      # Optional section.
      # By default, one connection will be specified with the "127.0.0.1:6379" value.
      addrs:
        - "REDIS_HOST:REDIS_PORT"

      # Optional section.
      # Default: ""
      username: ""

      # Optional section.
      # Default: ""
      password: ""
metrics:
  address: "0.0.0.0:2112"
logs:
  mode: production
  level: debug
  encoding: console
status:
    address: localhost:2114
