version: '3'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  # open telemetry tracing
  env:
    - OTEL_SERVICE_NAME: php
    - OTEL_TRACES_EXPORTER: otlp
    - OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    - OTEL_EXPORTER_OTLP_ENDPOINT: http://0.0.0.0:4318
    - OTEL_PHP_TRACES_PROCESSOR: simple
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers", "http_metrics", "otel" ]
  max_request_size: 100
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 1h
    destroy_timeout: 1h
    max_jobs: 0
    supervisor:
      max_worker_memory: 128
      exec_ttl: 1h
metrics:
  address: "0.0.0.0:2112"
logs:
  mode: production
  level: debug
  encoding: console
status:
    address: localhost:2114
