version: '3'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers", "http_metrics", "otel" ]
  max_request_size: 100
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 1h
    destroy_timeout: 1h
    max_jobs: 0
    supervisor:
      max_worker_memory: 128
      exec_ttl: 1h
metrics:
  address: "0.0.0.0:2112"
otel:
  resource:
    service_name: "rr_telemetry"
    service_version: "1.0.0"
    service_namespace: "RR-TELEMETRY"
    service_instance_id: "UUID"
  insecure: true
  compress: false
  exporter: otlp
  endpoint: 127.0.0.1:4317
logs:
  mode: production
  level: debug
  encoding: console
status:
    address: localhost:2114
