version: '2.7'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers" ]
  max_request_size: 20
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 100s
    destroy_timeout: 100s
    supervisor:
      max_worker_memory: 128
      exec_ttl: 100s
redis:
  # Required section.
  # Should be "redis" for the redis driver.
  driver: redis

  config:
    # Optional section.
    # By default, one connection will be specified with the "127.0.0.1:6379" value.
    addrs:
      - "127.0.0.1:6379"

    # Optional section.
    # Default: ""
    username: ""

    # Optional section.
    # Default: ""
    password: ""

    # Optional section.
    # Default: 0
    db: 0

    # Optional section.
    # Default: 0 (equivalent to the default value of 5 seconds)
    dial_timeout: 0

    # Optional section.
    # Default: 0 (equivalent to the default value of 3 retries)
    max_retries: 0

    # Optional section.
    # Default: 0 (equivalent to the default value of 8ms)
    min_retry_backoff: 0

    # Optional section.
    # Default: 0 (equivalent to the default value of 512ms)
    max_retry_backoff: 0

    # Optional section.
    # Default: 0 (equivalent to the default value of 10 connections per CPU).
    pool_size: 0

    # Optional section.
    # Default: 0 (do not use idle connections)
    min_idle_conns: 0

    # Optional section.
    # Default: 0 (do not close aged connections)
    max_conn_age: 0

    # Optional section.
    # Default: 0 (equivalent to the default value of 3s)
    read_timeout: 0

    # Optional sectinon.
    # Default: 0 (equivalent to the value specified in the "read_timeout" section)
    write_timeout: 0

    # Optional section.
    # Default: 0 (equivalent to the value specified in the "read_timeout" + 1s)
    pool_timeout: 0

    # Optional section.
    # Default: 0 (equivalent to the default value of 5m)
    idle_timeout: 0

    # Optional section.
    # Default: 0 (equivalent to the default value of 1m)
    idle_check_freq: 0

    # Optional section.
    # Default: false
    read_only: false
logs:
  mode: production
  level: debug
  encoding: json
status:
    address: localhost:2114
