version: '3'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers", "http_metrics" ]
  max_request_size: 128
  access_logs: false
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 10m
    destroy_timeout: 10m
    num_workers: 2
    max_queue_size: 100
    supervisor:
      max_worker_memory: 128
      exec_ttl: 1h
metrics:
  address: "0.0.0.0:2112"
logs:
  mode: production
  level: debug
  output: [stdout]
status:
    address: localhost:2114
