name: Push to docker hub

on:
  release:
    types: [published]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # get release tag version
    - name: Get release tag
      id: get_tag
      run: echo "tag=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

    # build docker image with a tag
    - name: build docker image
      run: |
        docker build -t laravel-backend/nginx-php-server:${{ steps.get_tag.outputs.tag }} .
    
    # push image to docker hub
    - name: push to docker
      run: docker push laravel-backend/nginx-php-server:${{ steps.get_tag.outputs.tag }}
      
