name: Push to docker hub

on:
  push:
    branches:
      - octane-server

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # get release tag version
    # - name: Get release tag
    #   id: get_tag
    #   run: echo "tag=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

    - name: Docker build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/octane-road-runner-server:lastest -f RoadRunner.Alpine.Dockerfile .
    
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/octane-road-runner-server:lastest
